# Generated by Django 4.2.7 on 2026-05-12 19:24

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trips', '0002_tasktemplate_task_unique_task_template_per_trip_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkTask',
            fields=[
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('trips.task',),
        ),
        migrations.CreateModel(
            name='WorkTaskTemplate',
            fields=[
            ],
            options={
                'verbose_name': 'Task Template',
                'verbose_name_plural': 'Task Templates',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('trips.tasktemplate',),
        ),
    ]
