# Generated by Django 4.2.7 on 2026-05-13 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0010_tasktemplatepack'),
        ('work_tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkTaskTemplatePack',
            fields=[
            ],
            options={
                'verbose_name': 'Task Template Pack',
                'verbose_name_plural': 'Task Template Packs',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('trips.tasktemplatepack',),
        ),
    ]
