# Generated by Django 4.2.7 on 2026-05-12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("staff_users", "0001_initial"),
        ("trips", "0003_remove_employee_role_delete_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="StaffEmployee",
            fields=[],
            options={
                "verbose_name": "Employee",
                "verbose_name_plural": "Employees",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("trips.employee",),
        ),
    ]
