# Generated by Django 4.2.7 on 2026-05-13 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerTripHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_name', models.CharField(max_length=180)),
                ('trip_start_date', models.DateField()),
                ('trip_end_date', models.DateField()),
                ('money_spent', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_history', to='crm.customer')),
            ],
            options={
                'verbose_name_plural': 'customer trip history',
                'ordering': ['-trip_start_date', 'trip_name', 'id'],
            },
        ),
    ]
