# Generated by Django 5.2.14 on 2026-05-14 14:10

import django.db.models.deletion
from django.db import migrations, models


def seed_customer_document_types(apps, schema_editor):
    CustomerDocumentType = apps.get_model("crm", "CustomerDocumentType")
    document_types = [
        ("Passport", "Customer passport scans or photos."),
        ("Government ID", "Driver licenses or other government-issued IDs."),
        ("Invoice", "Customer invoices and payment documents."),
        ("Waiver", "Signed waivers and release forms."),
        ("Travel Insurance", "Insurance policy and coverage documents."),
        ("Other", "Documents that do not fit another standard type."),
    ]
    for sort_order, (name, description) in enumerate(document_types, start=10):
        CustomerDocumentType.objects.get_or_create(
            name=name,
            defaults={
                "description": description,
                "sort_order": sort_order,
                "is_active": True,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_customertriphistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='customerdocument',
            name='document_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='crm.customerdocumenttype'),
        ),
        migrations.RunPython(seed_customer_document_types, migrations.RunPython.noop),
    ]
