# Generated by Codex on 2026-09-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0003_customerdocumenttype_customerdocument_document_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="woocommerce_order_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="customer",
            name="woocommerce_total_spend",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
