# Generated by Django 4.2.7 on 2026-05-12 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_tasktemplate_task_unique_task_template_per_trip_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='role',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
