# Generated by Django 4.2.7 on 2026-05-12 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_remove_employee_role_delete_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='days_to_before_trip',
            field=models.IntegerField(blank=True, help_text='Days from trip start. Use negative numbers before the trip and positive numbers after.', null=True),
        ),
        migrations.AlterField(
            model_name='tasktemplate',
            name='days_to_before_trip',
            field=models.IntegerField(blank=True, help_text='Days from trip start. Use negative numbers before the trip and positive numbers after.', null=True),
        ),
    ]
