# Generated by Codex on 2026-05-12

from django.db import migrations


def drop_positive_day_offset_constraints(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return

    schema_editor.execute(
        """
        ALTER TABLE trips_tasktemplate
        DROP CONSTRAINT IF EXISTS trips_tasktemplate_days_to_before_trip_check;
        """
    )
    schema_editor.execute(
        """
        ALTER TABLE trips_task
        DROP CONSTRAINT IF EXISTS trips_task_days_to_before_trip_check;
        """
    )


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0004_alter_task_days_to_before_trip_and_more"),
    ]

    operations = [
        migrations.RunPython(
            drop_positive_day_offset_constraints,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
