# Generated by Codex on 2026-05-12

from django.db import migrations, models


def backfill_trip_names(apps, schema_editor):
    Trip = apps.get_model("trips", "Trip")
    for trip in Trip.objects.filter(name__isnull=True):
        trip.name = f"Trip #{trip.pk}"
        trip.save(update_fields=["name"])


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0005_drop_positive_day_offset_constraints"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="name",
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
        migrations.RunPython(backfill_trip_names, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="trip",
            name="name",
            field=models.CharField(max_length=180),
        ),
    ]

