# Generated by Django 4.2.7 on 2026-05-12 20:20

from django.db import migrations, models


def copy_user_groups_to_employee_roles(apps, schema_editor):
    table_names = schema_editor.connection.introspection.table_names()
    if "staff_users_user" not in table_names or "trips_employee" not in table_names:
        return

    Employee = apps.get_model("trips", "Employee")
    User = apps.get_model("staff_users", "User")

    for employee in Employee.objects.all():
        user = User.objects.filter(pk=employee.user_id).first()
        if user:
            employee.roles.set(user.groups.all())


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('staff_users', '0002_staffemployee'),
        ('trips', '0006_trip_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='roles',
            field=models.ManyToManyField(blank=True, help_text="Employee permission roles. These sync to the linked user's groups.", related_name='employees', to='auth.group'),
        ),
        migrations.RunPython(
            copy_user_groups_to_employee_roles,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
