# Generated by Django 4.2.7 on 2026-05-12 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0007_employee_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='trip_leader',
        ),
        migrations.AddField(
            model_name='trip',
            name='trip_leader',
            field=models.ForeignKey(blank=True, help_text='Host employee going on the trip.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hosted_trips', to='trips.employee'),
        ),
    ]
