# Generated by Django 4.2.7 on 2026-05-13 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0009_trip_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskTemplatePack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=180, unique=True)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('task_templates', models.ManyToManyField(blank=True, related_name='packs', to='trips.tasktemplate')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
