# Generated by Django 4.2.7 on 2026-09-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0010_tasktemplatepack"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasktemplate",
            name="status",
            field=models.CharField(
                choices=[
                    ("not_started", "Not Started"),
                    ("in_progress", "In Progress"),
                    ("done", "Done"),
                ],
                default="not_started",
                help_text="Status assigned to new tasks created from this template.",
                max_length=20,
            ),
        ),
    ]
