# Generated by Django 5.2.17 on 2026-09-11 04:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0011_tasktemplate_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='customer_capacity',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum number of customers on this trip. Leave blank if undecided.', null=True, validators=[django.core.validators.MaxValueValidator(2147483647)]),
        ),
        migrations.AddField(
            model_name='trip',
            name='is_sold_out',
            field=models.BooleanField(default=False, help_text='Mark this when the trip has sold out, including past trips.', verbose_name='sold out'),
        ),
    ]
